# Generated by Django 5.1.4 on 2024-12-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
