# Generated by Django 5.1.4 on 2024-12-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scentapp', '0003_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
