# Generated by Django 5.1.4 on 2024-12-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scentapp', '0006_topnote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
